version: "3.9"

services:
  x509-rp:
    container_name: x509-rp
    image: x509-rp
    build:
      context: ./https
      dockerfile: Dockerfile
    links:
      - "x509"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - "443:443"

  x509:
    container_name: x509
    image: x509
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - "80:80"