version: "3.9"

services:
  SoundUNder_wa:
    container_name: x509
    image: x509
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - "80:80"